# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/liyan/cmake/bin/cmake

# The command to remove a file.
RM = /home/liyan/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liyan/vml/OpenVML

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liyan/vml/OpenVML

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/liyan/cmake/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/liyan/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/liyan/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/liyan/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/liyan/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/liyan/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/liyan/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liyan/vml/OpenVML/CMakeFiles /home/liyan/vml/OpenVML/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liyan/vml/OpenVML/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named openvml

# Build rule for target.
openvml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openvml
.PHONY : openvml

# fast build rule for target.
openvml/fast:
	$(MAKE) -f CMakeFiles/openvml.dir/build.make CMakeFiles/openvml.dir/build
.PHONY : openvml/fast

#=============================================================================
# Target rules for targets named openvml_static

# Build rule for target.
openvml_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openvml_static
.PHONY : openvml_static

# fast build rule for target.
openvml_static/fast:
	$(MAKE) -f CMakeFiles/openvml_static.dir/build.make CMakeFiles/openvml_static.dir/build
.PHONY : openvml_static/fast

#=============================================================================
# Target rules for targets named openvml_interface_core

# Build rule for target.
openvml_interface_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openvml_interface_core
.PHONY : openvml_interface_core

# fast build rule for target.
openvml_interface_core/fast:
	$(MAKE) -f interface/CMakeFiles/openvml_interface_core.dir/build.make interface/CMakeFiles/openvml_interface_core.dir/build
.PHONY : openvml_interface_core/fast

#=============================================================================
# Target rules for targets named openvml_driver_core

# Build rule for target.
openvml_driver_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openvml_driver_core
.PHONY : openvml_driver_core

# fast build rule for target.
openvml_driver_core/fast:
	$(MAKE) -f driver/CMakeFiles/openvml_driver_core.dir/build.make driver/CMakeFiles/openvml_driver_core.dir/build
.PHONY : openvml_driver_core/fast

#=============================================================================
# Target rules for targets named openvml_kernel_arm_cortexa15_core

# Build rule for target.
openvml_kernel_arm_cortexa15_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openvml_kernel_arm_cortexa15_core
.PHONY : openvml_kernel_arm_cortexa15_core

# fast build rule for target.
openvml_kernel_arm_cortexa15_core/fast:
	$(MAKE) -f kernel/CMakeFiles/openvml_kernel_arm_cortexa15_core.dir/build.make kernel/CMakeFiles/openvml_kernel_arm_cortexa15_core.dir/build
.PHONY : openvml_kernel_arm_cortexa15_core/fast

#=============================================================================
# Target rules for targets named openvml_ref

# Build rule for target.
openvml_ref: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openvml_ref
.PHONY : openvml_ref

# fast build rule for target.
openvml_ref/fast:
	$(MAKE) -f reference/CMakeFiles/openvml_ref.dir/build.make reference/CMakeFiles/openvml_ref.dir/build
.PHONY : openvml_ref/fast

#=============================================================================
# Target rules for targets named misc_test

# Build rule for target.
misc_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 misc_test
.PHONY : misc_test

# fast build rule for target.
misc_test/fast:
	$(MAKE) -f test/CMakeFiles/misc_test.dir/build.make test/CMakeFiles/misc_test.dir/build
.PHONY : misc_test/fast

#=============================================================================
# Target rules for targets named run_vml_test

# Build rule for target.
run_vml_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_vml_test
.PHONY : run_vml_test

# fast build rule for target.
run_vml_test/fast:
	$(MAKE) -f test/CMakeFiles/run_vml_test.dir/build.make test/CMakeFiles/run_vml_test.dir/build
.PHONY : run_vml_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... openvml_static"
	@echo "... openvml"
	@echo "... openvml_interface_core"
	@echo "... openvml_driver_core"
	@echo "... openvml_kernel_arm_cortexa15_core"
	@echo "... openvml_ref"
	@echo "... misc_test"
	@echo "... run_vml_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

